

service: WhatsAppPush

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: sls-user
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [DynamoTemplatesTable, Arn]
  environment:
    tableName: ${self:custom.tableName}

package:
  individually: true

custom:
  tableName: Templates

functions:
  createTemplate:
    handler: lambdas/handlers/createTemplate.handler
    events:
      - httpApi:
          method: post
          path: /templates


resources:
  Resources:
    DynamoTemplatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: template_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: template_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST


plugins:
  - serverless-webpack
  # - serverless-offline
